use_frameworks!

target 'SalesManLogin_Category_Example' do
  pod 'SalesManLogin_Category', :path => '../'
  pod 'CTMediator'
target 'SalesManLogin_Category_Tests' do
    inherit! :search_paths

    
  end
end
